import React from 'react'

function Dropdown() {
  return (
    <>
          <option> Select Currency</option>
          <option value="AFN">AFN - Afghan Afghani - ؋</option>
          <option value="ALL">ALL - Albanian Lek - L</option>
          <option value="DZD">DZD - Algerian Dinar - د.ج</option>
          <option value="AOA">AOA - Angolan Kwanza - Kz</option>
          <option value="ARS">ARS - Argentine Peso - $</option>
          <option value="AMD">AMD - Armenian Dram - ֏</option>
          <option value="AWG">AWG - Aruban Florin - ƒ</option>
          <option value="AUD">AUD - Australian Dollar - A$</option>
          <option value="AZN">AZN - Azerbaijani Manat - ₼</option>
          <option value="BSD">BSD - Bahamian Dollar - $</option>
          <option value="BHD">BHD - Bahraini Dinar - .د.ب</option>
          <option value="BDT">BDT - Bangladeshi Taka - ৳</option>
          <option value="BBD">BBD - Barbadian Dollar - $</option>
          <option value="BYN">BYN - Belarusian Ruble - Br</option>
          <option value="BZD">BZD - Belize Dollar - BZ$</option>
          <option value="BMD">BMD - Bermudan Dollar - $</option>
          <option value="BTN">BTN - Bhutanese Ngultrum - Nu.</option>
          <option value="BTC">BTC - Bitcoin - ₿</option>
          <option value="BOB">BOB - Bolivian Boliviano - Bs.</option>
          <option value="BAM">BAM - Bosnia-Herzegovina Convertible Mark - KM</option>
          <option value="BWP">BWP - Botswanan Pula - P</option>
          <option value="BRL">BRL - Brazilian Real - R$</option>
          <option value="GBP">GBP - British Pound Sterling - £</option>
          <option value="BND">BND - Brunei Dollar - $</option>
          <option value="BGN">BGN - Bulgarian Lev - лв</option>
          <option value="BIF">BIF - Burundian Franc - FBu</option>
          <option value="KHR">KHR - Cambodian Riel - ៛</option>
          <option value="CAD">CAD - Canadian Dollar - C$</option>
          <option value="CVE">CVE - Cape Verdean Escudo - $</option>
          <option value="KYD">KYD - Cayman Islands Dollar - $</option>
          <option value="XOF">XOF - CFA Franc BCEAO - CFA</option>
          <option value="XAF">XAF - CFA Franc BEAC - FCFA</option>
          <option value="XPF">XPF - CFP Franc - ₣</option>
          <option value="CLP">CLP - Chilean Peso - $</option>
          <option value="CNY">CNY - Chinese Yuan - ¥</option>
          <option value="COP">COP - Colombian Peso - $</option>
          <option value="KMF">KMF - Comorian Franc - CF</option>
          <option value="CDF">CDF - Congolese Franc - FC</option>
          <option value="CRC">CRC - Costa Rican Colón - ₡</option>
          <option value="HRK">HRK - Croatian Kuna - kn</option>
          <option value="CUC">CUC - Cuban Convertible Peso - $</option>
          <option value="CZK">CZK - Czech Koruna - Kč</option>
          <option value="DKK">DKK - Danish Krone - kr</option>
          <option value="DJF">DJF - Djiboutian Franc - Fdj</option>
          <option value="DOP">DOP - Dominican Peso - RD$</option>
          <option value="XCD">XCD - East Caribbean Dollar - EC$</option>
          <option value="EGP">EGP - Egyptian Pound - £</option>
          <option value="ERN">ERN - Eritrean Nakfa - Nfk</option>
          <option value="ETB">ETB - Ethiopian Birr - Br</option>
          <option value="EUR">EUR - Euro - €</option>
          <option value="FKP">FKP - Falkland Islands Pound - £</option>
          <option value="FJD">FJD - Fijian Dollar - FJ$</option>
          <option value="GMD">GMD - Gambian Dalasi - D</option>
          <option value="GEL">GEL - Georgian Lari - ₾</option>
          <option value="GHS">GHS - Ghanaian Cedi - ₵</option>
          <option value="GIP">GIP - Gibraltar Pound - £</option>
          <option value="GTQ">GTQ - Guatemalan Quetzal - Q</option>
          <option value="GNF">GNF - Guinean Franc - FG</option>
          <option value="GYD">GYD - Guyanaese Dollar - $</option>
          <option value="HTG">HTG - Haitian Gourde - G</option>
          <option value="HNL">HNL - Honduran Lempira - L</option>
          <option value="HKD">HKD - Hong Kong Dollar - HK$</option>
          <option value="HUF">HUF - Hungarian Forint - Ft</option>
          <option value="ISK">ISK - Icelandic Króna - kr</option>
          <option value="INR">INR - Indian Rupee - ₹</option>
          <option value="IDR">IDR - Indonesian Rupiah - Rp</option>
          <option value="IRR">IRR - Iranian Rial - ﷼</option>
          <option value="IQD">IQD - Iraqi Dinar - ع.د</option>
          <option value="ILS">ILS - Israeli New Sheqel - ₪</option>
          <option value="JMD">JMD - Jamaican Dollar - J$</option>
          <option value="JPY">JPY - Japanese Yen - ¥</option>
          <option value="JOD">JOD - Jordanian Dinar - د.ا</option>
          <option value="KZT">KZT - Kazakhstani Tenge - ₸</option>
          <option value="KES">KES - Kenyan Shilling - KSh</option>
          <option value="KWD">KWD - Kuwaiti Dinar - د.ك</option>
          <option value="KGS">KGS - Kyrgystani Som - с</option>
          <option value="LAK">LAK - Laotian Kip - ₭</option>
          <option value="LBP">LBP - Lebanese Pound - ل.ل</option>
          <option value="LSL">LSL - Lesotho Loti - L</option>
          <option value="LRD">LRD - Liberian Dollar - $</option>
          <option value="LYD">LYD - Libyan Dinar - ل.د</option>
          <option value="MOP">MOP - Macanese Pataca - MOP$</option>
          <option value="MKD">MKD - Macedonian Denar - ден</option>
          <option value="MGA">MGA - Malagasy Ariary - Ar</option>
          <option value="MWK">MWK - Malawian Kwacha - MK</option>
          <option value="MYR">MYR - Malaysian Ringgit - RM</option>
          <option value="MVR">MVR - Maldivian Rufiyaa - Rf</option>
          <option value="MRU">MRU - Mauritanian Ouguiya - UM</option>
          <option value="MUR">MUR - Mauritian Rupee - ₨</option>
          <option value="MXN">MXN - Mexican Peso - $</option>
          <option value="MDL">MDL - Moldovan Leu - L</option>
          <option value="MNT">MNT - Mongolian Tugrik - ₮</option>
          <option value="MAD">MAD - Moroccan Dirham - د.م.</option>
          <option value="MZN">MZN - Mozambican Metical - MT</option>
          <option value="MMK">MMK - Myanmar Kyat - Ks</option>
          <option value="NAD">NAD - Namibian Dollar - $</option>
          <option value="NPR">NPR - Nepalese Rupee - ₨</option>
          <option value="ANG">ANG - Netherlands Antillean Guilder - ƒ</option>
          <option value="TWD">TWD - New Taiwan Dollar - NT$</option>
          <option value="NZD">NZD - New Zealand Dollar - $</option>
          <option value="NIO">NIO - Nicaraguan Córdoba - C$</option>
          <option value="NGN">NGN - Nigerian Naira - ₦</option>
          <option value="KPW">KPW - North Korean Won - ₩</option>
          <option value="NOK">NOK - Norwegian Krone - kr</option>
          <option value="OMR">OMR - Omani Rial - ر.ع.</option>
          <option value="PKR">PKR - Pakistani Rupee - ₨</option>
          <option value="PAB">PAB - Panamanian Balboa - B/.</option>
          <option value="PGK">PGK - Papua New Guinean Kina - K</option>
          <option value="PYG">PYG - Paraguayan Guarani - ₲</option>
          <option value="PEN">PEN - Peruvian Sol - S/</option>
          <option value="PHP">PHP - Philippine Peso - ₱</option>
          <option value="PLN">PLN - Polish Zloty - zł</option>
          <option value="QAR">QAR - Qatari Rial - ر.ق</option>
          <option value="RON">RON - Romanian Leu - lei</option>
          <option value="RUB">RUB - Russian Ruble - ₽</option>
          <option value="RWF">RWF - Rwandan Franc - FRw</option>
          <option value="SAR">SAR - Saudi Riyal - ر.س</option>
          <option value="SDG">SDG - Sudanese Pound - ج.س.</option>
          <option value="SRD">SRD - Surinamese Dollar - $</option>
          <option value="SZL">SZL - Swazi Lilangeni - L</option>
          <option value="SEK">SEK - Swedish Krona - kr</option>
          <option value="CHF">CHF - Swiss Franc - CHF</option>
          <option value="STN">STN - São Tomé and Príncipe Dobra - Db</option>
          <option value="USD">USD - United State Dollar - $</option>
          <option value="VES">VES - Venezuelan Bolívar - Bs.S</option>
          <option value="ZMW">ZMW - Zambian Kwacha - ZK</option>
    </>
  )
}

export default Dropdown